First Commit
jonart/NewYorkTimes pull request #1
Opened 2019-03-15 10:04 UTC by jonart

First

2019-03-16 21:11 UTC, georgyR requested changes

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/SharedPref.java
> +            mSharedPreferences.edit().putBoolean(FIRST_LAUNCH, true);
нужно еще добавить `.commit()` иначе ничего не записывается в sharPref

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/IntroActivity.java
> +    private void startSecondActivity() {
Если ты помнишь в академии говорили что нужно придерживаться кодстайл (можно своего собственного или взять уже готовый). Это позволяется быстрей разбираться в своем старом коде и другим людям в твоем.
Пример код стайл https://github.com/RedMadRobot/kotlin-style-guide. Обычно принято писать методы в таком порядке https://github.com/RedMadRobot/kotlin-style-guide#структура-класса В данном случае private в самый низ

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/IntroActivity.java
> +    private CompositeDisposable compositeDisposable = new CompositeDisposable();
уже видел что используешь в проекте венгерскую аннотацию. compositeDisposable чем хуже? Определись, ты ее используешь все таки везде или нигде)

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/IntroActivity.java
> +        startActivity(new Intent(this, NewsListActivity.class));
лучше когда одна активити не создает интент другой, а делегирует это другой активити чей интент нужен. 
```
public static Intent getStartIntent(Context context) {
        return new Intent(context, NewsListActivity.class);
}
```

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +    List<NewsItem> news = new ArrayList<>();
тут неправильная последовательно полей. Гляну в других классах-активити, там у тебя с этим все ок https://github.com/RedMadRobot/kotlin-style-guide#структура-класса

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            mRecycler.setLayoutManager(new GridLayoutManager(this, 2));
захардкожена 2

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        mRecycler.addItemDecoration(new ItemDecorator(16));
захардкодил 16

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +public class NewsListActivity extends AppCompatActivity implements MyClickListener {
Было бы классно навести порядок в последовательности методов в этом классе https://github.com/RedMadRobot/kotlin-style-guide#структура-класса

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        loadData("Home".toLowerCase());
1. Хардкод "Home". 2. Категории можно запихнуть в enum, их же ограниченное количество, вполне подходит

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        if (category.contains(" ")) {category = category.replace(" ", "");}
а зачем тут пробелы удалять? И можно без `contains()`. `replace()` и так пробегает и чекает их

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +                    }, Throwable::printStackTrace);
если уйдет в onError, то прогресс так и останется, надо добавить `showProgressBar(false)`. Или в цепочку добавить `doFinally()` чтобы не дублировать код

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            Toast.makeText(this, "Internet is not available", Toast.LENGTH_SHORT).show();
это уже придирка, но какой toast в 2k19?)) Snackbar!

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +    public boolean isOnline(){
можно и без этого метода. Если не будет сети, то цепочка rx свалиться в onError при загрузке новостей

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        intent.putExtra(NewsDetailActivity.URL, item.getUrl());
`getStartIntent()` бы сюда как писал выше

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            mDisposable = RestApi.getInstance().getApi()
лучше уже сразу весь код связанный с создание api, или, например, с БД скрывать от активити. И это апи тебе понадобится на других экранах далее, и не создавать же на каждом экране объект для работы с апи. Поэтому пока можно вынести процесс создание api в Application и написать статический метод доступа к инстансу

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsDetailActivity.java
> +//        webSettings.setJavaScriptEnabled(true);
мертвый код, его бы убрать

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/AdViewHolder.java
> +public class AdViewHolder extends RecyclerView.ViewHolder {
мертвый код

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    public int getItemViewType(int position) {
а что делает здесь этот метод?

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsHolder.java
> +    SimpleDateFormat mSimpleDateFormat = new SimpleDateFormat("yyyy.MM.dd");
не используется нигде, надо удалять

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/StoryMappers.java
> +    private static final String MULTIMEDIA_TYPE_IMAGE = "image";
не используется

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    public NewsAdapter(MyClickListener onClick) {
public методы по кодстайлу ниже должны быть

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/Category.java
> +//public enum Category {
классный класс, его бы заюзать

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/DataUtils.java
> +//public class DataUtils {
удаляем мертвечину

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/NewsItem.java
> +//    public String getPublishDate(String dateFormatString) {
я понимаю жало свой код удалять)) но комментарии не для этого придумали, чтобы в них мертвый код держать

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtn1.setOnClickListener(view -> openLink("https://t.me/EvgeniyKam"));
было бы неплохо вынести эти линки в enum

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtn1 = findViewById(R.id.ib_first);
нейминг от бога)) Давай что-нибудь по конкретней)

2019-03-16 21:11 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        intent.putExtra(Intent.EXTRA_TEXT, mEditText.getText().toString());
чтобы активити не засорять логикой, можно вынести создание интента в утильный класс. Это первый шаг на пути избавления активити от логики несвязанной с отображением

2019-03-16 21:11 UTC, georgyR commented on app/src/main/res/layout/activity_intro.xml
> +        android:text="INTRO"/>
в ресурсы вынести бы

2019-03-16 21:11 UTC, georgyR commented on app/src/main/res/layout/linear.xml
> +            android:id="@+id/ib_first"
царский нейминг из лаб по программированию на pascal в универе))) ib_telegram куда круче будет) ниже тоже самое

2019-03-19 09:30 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/SharedPref.java
> +            mSharedPreferences.edit().putBoolean(FIRST_LAUNCH, true);
Да спасибо, забыл добавить.

2019-03-19 09:30 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/IntroActivity.java
> +    private void startSecondActivity() {
Стараюсь придерживаться, как раз кодстайла академии.

2019-03-19 09:30 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/IntroActivity.java
> +    private CompositeDisposable compositeDisposable = new CompositeDisposable();
исправил на mCompositeDisposable

2019-03-19 09:32 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            mRecycler.setLayoutManager(new GridLayoutManager(this, 2));
Какие предложение есть?

2019-03-19 09:33 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            mRecycler.setLayoutManager(new GridLayoutManager(this, 2));
исправил

2019-03-19 09:34 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        mRecycler.addItemDecoration(new ItemDecorator(16));
Исправил.

2019-03-19 09:35 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +public class NewsListActivity extends AppCompatActivity implements MyClickListener {
Не понял что именно необходимо.

2019-03-19 09:37 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        loadData("Home".toLowerCase());
1. исправил. 2. Пробовал через енум но не смог скормить их адаптеру спиннера.

2019-03-19 09:39 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        if (category.contains(" ")) {category = category.replace(" ", "");}
Пробелы надо удалять чтоб категорию грузил, иначе с пробелом такие категории не находит как 
Убрал contains оставил только replace

2019-03-19 09:41 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +                    }, Throwable::printStackTrace);
Исправил на  throwable -> showProgressBar(false));

2019-03-19 09:42 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            Toast.makeText(this, "Internet is not available", Toast.LENGTH_SHORT).show();
Исправил.

2019-03-19 09:43 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +    public boolean isOnline(){
По условию задачи надо же проверять интернет.

2019-03-19 10:03 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +            mDisposable = RestApi.getInstance().getApi()
Вынес в App

2019-03-19 10:04 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsDetailActivity.java
> +//        webSettings.setJavaScriptEnabled(true);
Убрал

2019-03-19 10:09 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/AdViewHolder.java
> +public class AdViewHolder extends RecyclerView.ViewHolder {
Убрал.

2019-03-19 10:10 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    public int getItemViewType(int position) {
Это мы делали выбор из 2 новостей разного формата, например текстовая, а потом новость-картинка.

2019-03-19 10:20 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/StoryMappers.java
> +    private static final String MULTIMEDIA_TYPE_IMAGE = "image";
Убрал

2019-03-19 10:22 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    public NewsAdapter(MyClickListener onClick) {
А если они все у меня паблик??? куда мне перемещать их?

2019-03-19 10:23 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/Category.java
> +//public enum Category {
Не прокатил, потому что не смог с ним ничего придумать.

2019-03-19 10:23 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/DataUtils.java
> +//public class DataUtils {
Удалил.

2019-03-19 10:25 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/NewsItem.java
> +//    public String getPublishDate(String dateFormatString) {
Нет, не жалко :-)

2019-03-19 10:30 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtn1.setOnClickListener(view -> openLink("https://t.me/EvgeniyKam"));
Не подружился с Enumами , вынес в строки.
 mImBtn1.setOnClickListener(view -> openLink(getString(R.string.telegram)));
        mImBtn2.setOnClickListener(view -> openLink(getString(R.string.vk)));
        mImBtn3.setOnClickListener(view -> openLink(getString(R.string.github)));

2019-03-19 10:33 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtn1 = findViewById(R.id.ib_first);
Исправил нейминг
 mImBtnTelegram = findViewById(R.id.ib_telegram);
        mImBtnVk = findViewById(R.id.ib_vk);
        mImBtnGit = findViewById(R.id.ib_github);
        mButtonSendComment = findViewById(R.id.btn_send_comment);
        mLinearLayout = findViewById(R.id.my_linear);
        mEditTextMessage = findViewById(R.id.et_message);

2019-03-19 10:35 UTC, jonart commented on app/src/main/res/layout/activity_intro.xml
> +        android:text="INTRO"/>
текст убрал.

2019-03-19 10:36 UTC, jonart commented on app/src/main/res/layout/linear.xml
> +            android:id="@+id/ib_first"
Исправил уже.

2019-03-25 18:55 UTC, georgyR requested changes

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +public class NewsListActivity extends AppCompatActivity implements MyClickListener {
методы в разнобой идут, не отсортированы по модификаторам

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +    private EditText mEditTextMessage;
Опять же по кодстайлку. Если ты юзаешь сокращенные обозначения для view, то юзай их до конца. То есть если ImBtn, то пиши везде уже Btn, Et и прочее или наоборот полные названия везде

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtnTelegram.setOnClickListener(view -> openLink(getString(R.string.telegram)));
обычно ресурсы используют для обычных надписей, которые в теории могу быть переведены на другой язык. Ссылки и похожие данные не хранят. Но если тебе так нравиться, то ок.

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
>          intent.putExtra(Intent.EXTRA_EMAIL, new String[]{"jonart2008@gmail.com"});
А чем вот почка хуже ссылки на телеграм?) Почему ее не засунул в ресурсы?

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    public Api getApi(){
public метод наверх. 
И походу ты вкурсе про @ NonNull @ Nullable аннотации)). Значит их будем везде расставлять, в java без них жить страшно и больно

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    private OkHttpClient buildOkHttpClient(){
@ NonNull или @ Nullable аннотации

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    private Retrofit buildRetrofit(@NonNull OkHttpClient client){
@ NonNull или @ Nullable аннотация над методом

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
@ Nullable аннотация у параметра

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/App.java
> +    public static SharedPref getSharedPref() {
статик метод в самый верх после переменных

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/App.java
> +    public static Api getRestApi() {
статик метод в самый верх после переменных

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    public RestApi(){
Вверх после статик методов

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    }
Сейчас же у тебя только одна карточка, разве нет? Если так оно и есть, то можно удалять этот метод

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    void setItems(List<NewsEntity> items) {
в самый низ этот метод

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsDetailActivity.java
> +//        webView.loadUrl(getIntent().getStringExtra(URL));
удаляем)

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        //Intent intent = NewsDetailActivity.getStartIntent(this);
был такой хороший метод и ты его закомментил 😢

2019-03-25 18:55 UTC, georgyR commented on app/src/main/java/ru/evgeniy/androidacademy/App.java
> +    private static Api mApi;
Так может все поля сделать без статик как у mDatabase?

2019-03-25 19:16 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +public class NewsListActivity extends AppCompatActivity implements MyClickListener {
Исправлено.

2019-03-25 19:20 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +    private EditText mEditTextMessage;
Исправил

2019-03-25 19:21 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +        mImBtnTelegram.setOnClickListener(view -> openLink(getString(R.string.telegram)));
Исправил

2019-03-25 19:22 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
>          intent.putExtra(Intent.EXTRA_EMAIL, new String[]{"jonart2008@gmail.com"});
Исправил

2019-03-25 19:22 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    public Api getApi(){
Расставил

2019-03-25 19:23 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    private OkHttpClient buildOkHttpClient(){
Исправил

2019-03-25 19:23 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    private Retrofit buildRetrofit(@NonNull OkHttpClient client){
Исправил

2019-03-25 19:23 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/Activity/AboutActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
Исправил

2019-03-25 19:24 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/App.java
> +    public static SharedPref getSharedPref() {
Исправил

2019-03-25 19:24 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/App.java
> +    public static Api getRestApi() {
Исправил

2019-03-25 19:24 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/data/network/RestApi.java
> +    public RestApi(){
Исправил

2019-03-25 19:25 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsAdapter.java
> +    void setItems(List<NewsEntity> items) {
Исправил

2019-03-25 19:25 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsDetailActivity.java
> +//        webView.loadUrl(getIntent().getStringExtra(URL));
Удалил

2019-03-25 19:25 UTC, jonart commented on app/src/main/java/ru/evgeniy/androidacademy/news/NewsListActivity.java
> +        //Intent intent = NewsDetailActivity.getStartIntent(this);
Раскоментил

2019-03-25 20:01 UTC, merged