News editor
jonart/NewYorkTimes pull request #2
Opened 2019-04-02 13:03 UTC by jonart

2019-04-04 19:09 UTC, georgyR commented
Чтобы создать ветку коммит не нужен)

2019-04-05 11:48 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +        mTextNews = findViewById(R.id.text_editor_news)
Прежне, чем писать на Котлине, советовал бы ознакомиться с примерами code style`ов
[https://github.com/hhru/android-style-guide/blob/master/docs/kotlin-style-guide.md](HH)

[https://developer.android.com/kotlin/style-guide](Google)

[https://kotlinlang.org/docs/reference/coding-conventions.html](Kotlin)

[https://github.com/RedMadRobot/kotlin-style-guide](RmR)

всех этих mSomething не видел

2019-04-05 11:48 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +        mDisposable = Completable.fromAction { getNewsDao().updateNewsById(id, title, fullText) }
Все эти Disposables нужно складывать в класс CompositeDisposable, это массив, а не единичное значение. А так ты кучу подписок в одну переменную добавляешь! В чем тут профит?!

2019-04-05 11:56 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
> +        reloadNews();
В чем смысл вызовов самописных функций до вызова функций super(родителя)? У тебя родитель AppCompatActivity, ты туда на почти 100% уверен, ничего специфического не написал. Я не сталкивался с таким, вот и спрашиваю. reloadNews скорее всего просто инфу выводят, а не как-то изменяют родительское поведение onResume

2019-04-05 11:56 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>          mDisposable.dispose();
Очищать массив точно нет никакого смысла до родительского onStop

2019-04-06 13:48 UTC, georgyR requested changes

2019-04-06 13:48 UTC, georgyR commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="ru.evgeniy.nytimes.news.EditorActivity"></activity>
пустое тело тега, схопни как у других activity

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +                .subscribe { newsEntity:NewsEntity ->
тип можно не указывать, обычно все так и делают

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    private lateinit var mButtonSave: Button
мастхев в мире kotlin на android https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding . Давай переедешь на эту штуку. Кода сразу меньше станет

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +        mButtonSave.setOnClickListener {
а зачем навешивание клик листенера лежит в этом методе? В onCreate ему место

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>              mSwipeRefreshLayout.setRefreshing(false);
а может progress свайпрефреш должен исчезать после того как данные загрузятся, а не сразу как ты его дернул?

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>      private Disposable mDisposable;
надо заменить на СompositeDisposable как писали выше. Перезаписывая в одну переменную disposable при этот не вызвав у старого значения `.dispose()` столкнешься с утечками памяти

2019-04-06 13:48 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/data/SharedPref.kt
> +    private val SHARED_PREF_NAME = "MY_SHARED_PREF"
константы по хорошему сделать `const` и засунуть в `companion object {..}`

2019-04-08 10:42 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
> +        reloadNews();
Исправил.

2019-04-08 10:42 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>          mDisposable.dispose();
Исправил

2019-04-08 10:43 UTC, jonart commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="ru.evgeniy.nytimes.news.EditorActivity"></activity>
Схлопнул,

2019-04-08 10:44 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +                .subscribe { newsEntity:NewsEntity ->
Исправил

2019-04-08 10:45 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    private lateinit var mButtonSave: Button
Уже почти везде где котлин на биндинге котлиновском

2019-04-08 10:48 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +        mButtonSave.setOnClickListener {
Убрал баттон вообще, сделал в тулбаре кнопку сохранения новости.

2019-04-08 10:49 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>              mSwipeRefreshLayout.setRefreshing(false);
Подумаю над этим, сейчас сделано так потому что при свайпе обновление из БД а не с инета.
я вообще думаю от ФАБа отказаться, и оставить только свайп

2019-04-08 10:50 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/NewsListActivity.java
>      private Disposable mDisposable;
Уже исправил+перевёл на фрагменты.

2019-04-08 10:50 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/data/SharedPref.kt
> +    private val SHARED_PREF_NAME = "MY_SHARED_PREF"
Пока что не понял что такое companion object {..} но учту.

2019-04-08 11:19 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/data/SharedPref.kt
> +    private val SHARED_PREF_NAME = "MY_SHARED_PREF"
Ну насчёт const согласен а в компаньона то зачем?

2019-04-08 15:31 UTC, merged