Fragments
jonart/NewYorkTimes pull request #3
Opened 2019-04-08 15:32 UTC by jonart

2019-04-08 21:00 UTC, georgyR requested changes

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
>      public static final int DELAY_TIME = 3;
почему не private?

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +    final int PAGE_COUNT = 3;
почему не private static?

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +    CircleIndicator mCircleIndicator;
private?

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +    CircleIndicator mCircleIndicator;
И кстати, венгерская нотацию можно не использовать в следующий проектах. Мы же в 2к19)

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
>      private void startSecondActivity() {
`startSecondActivity()`? помойму не очень ясный нейминг, примерно равносильный `startActivity2()`

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +        startActivity(new Intent(this, MainActivity.class));
создание интента должно быть не в этом классе, ты же знаешь где ему место

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/IntroFragment1.kt
> +class IntroFragment1 : Fragment() {
если посмотреть на все 3 IntroFragment, то это считай одно и тоже. Даже верста одна и та же. Можно заменить 1 фрагментом, 1 версткой и подсовывать нужную картинку параметром

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private var disposable: CompositeDisposable? = CompositeDisposable()
почему nullable тип? зачем var? Также можно тип не указывать и так сразу очевидно что это за тип

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private val ID_NEWS = "ID_NEWS"
companion object и const

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private var id_news:Int = 0
какой-то странный синтаксис, low-snake-case? не kotlin-java стайл точно

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +        if (arguments != null){
в котлине такого не пишут почти. Обычно все обзамывают `?.let {}` `?.apply{}` и прочим вот так
```
arguments?.apply {
            id_news = getInt(ID_NEWS)
            loadNews(id_news)
}
```

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +            id_news = arguments!!.getInt(ID_NEWS)
забудь про `!!`. Это как рассматривать дуло заряженной двухстволки))

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +            else -> {
можно без else

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +                else -> {
елсе не нужно

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private val SPACING = 16
в этот момент грустит один companion object (и парочку других, из соседних классов, где их нет)

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private var spinner: Spinner? = null
а где венгерская нотация?

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private var spinner: Spinner? = null
ниже еще пару таких полей

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private var spinner: Spinner? = null
lateinit. В котлине надо по максимум избегать nullable типом и жизнь станет проще

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    fun newInstance(): Fragment {
не забывай про то что в котлине можно писать вот так по красоте:
```
fun newInstance() = NewsListFragment()
```

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +                if (!nowCategory.isEmpty()) getNewsFromInternet(nowCategory)
скорей всего есть такой метод isNotEmpty(). Юзай его, намного читабельней

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +        val connectivityManager = context!!.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager?
`!!`двухстволку выпиливай)

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/data/SharedPref.kt
> +        const val SHARED_PREF_NAME = "MY_SHARED_PREF"
private и как и статику в джаве компаньон наверх

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    val ID_NEWS = "ID_NEWS"
компаньон конст прайват (чисто по классике)

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    private var disposable : CompositeDisposable? = CompositeDisposable()
без  `?`

2019-04-08 21:00 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +                ?.commit()
как много вопросиков)
Можно вот так от них избавиться
```

        activity?.supportFragmentManager?.apply {
            beginTransaction()
                    .replace(R.id.news_container, NewsDetailFragment().newInstance(item.id))
                    .addToBackStack(null)
                    .commit()
        }
```

2019-04-09 10:37 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
>      public static final int DELAY_TIME = 3;
Исправил обе константы на private static final

2019-04-09 10:37 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +    final int PAGE_COUNT = 3;
Исправил обе константы на private static final

2019-04-09 10:38 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +    CircleIndicator mCircleIndicator;
Исправил

2019-04-09 10:39 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
>      private void startSecondActivity() {
исправил на startSecondActivity

2019-04-09 10:54 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +        startActivity(new Intent(this, MainActivity.class));
Переделал. Вынес создание интент в Companion MainActivity

2019-04-09 10:55 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +        val connectivityManager = context!!.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager?
Заменил на ?.

2019-04-09 10:56 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/data/SharedPref.kt
> +        const val SHARED_PREF_NAME = "MY_SHARED_PREF"
Переместил наверх

2019-04-09 10:58 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    val ID_NEWS = "ID_NEWS"
Исправил

2019-04-09 10:58 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/news/EditorActivity.kt
> +    private var disposable : CompositeDisposable? = CompositeDisposable()
Исправил

2019-04-09 11:00 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +                ?.commit()
Сделал.

2019-04-09 11:26 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/IntroFragment1.kt
> +class IntroFragment1 : Fragment() {
Переделал на 1 фрагмент и 1 вёрстку.

2019-04-09 11:28 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private var disposable: CompositeDisposable? = CompositeDisposable()
Убрал ? и тип тоже убрал.

2019-04-09 11:32 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private val ID_NEWS = "ID_NEWS"
Исправил

2019-04-09 11:33 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +    private var id_news:Int = 0
Если ты про id_news испрвил на newsId

2019-04-09 11:36 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +        if (arguments != null){
Учту

2019-04-09 11:37 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +            id_news = arguments!!.getInt(ID_NEWS)
Исправил

2019-04-09 11:38 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +            else -> {
Ок

2019-04-09 11:39 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsDetailFragment.kt
> +                else -> {
Исправил

2019-04-09 11:39 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private val SPACING = 16
Переместил уже.

2019-04-09 11:41 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private var spinner: Spinner? = null
Ну на котлине я в венгерской и не пишу.

2019-04-09 11:41 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    private var spinner: Spinner? = null
Исправил

2019-04-09 11:42 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +    fun newInstance(): Fragment {
Ок учтёмс.

2019-04-09 11:43 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Fragments/NewsListFragment.kt
> +                if (!nowCategory.isEmpty()) getNewsFromInternet(nowCategory)
Исправил.

2019-04-10 09:50 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/fragments/IntroFragment.kt
> +            screenId = arguments!!.getInt(SCREEN_NUMBER)
arguments!! плохая история. Аргументы могут не задать и приплыли - НПЕ

2019-04-10 09:50 UTC, bugtsa commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +        compositeDisposable.dispose();
compositeDislosable.clear();

2019-04-10 09:57 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/IntroFragment.kt
> +            screenId = arguments!!.getInt(SCREEN_NUMBER)
Исправил на 
arguments?.apply {
                screenId = getInt(SCREEN_NUMBER)
                setImage()
            }

2019-04-10 09:58 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/Activity/IntroActivity.java
> +        compositeDisposable.dispose();
Исправил, не досмотрел )

2019-04-10 12:23 UTC, merged