Mvp
jonart/NewYorkTimes pull request #4
Opened 2019-04-12 15:39 UTC by jonart

2019-04-14 17:59 UTC, georgyR requested changes
Пройдись плз по всем фрагментам, презентерам и поправь публичные методы презентера. Фрагмент (или активити) должны сообщать о событии, а не командовать перезентеры что делать.
Также хорошо было бы создать базовый абстрактный класс перезентера. А то копипаст везде один и тот же: compositedisposable и его очистка в onDestroy в перезентере (тебе его еще нужно дописать).
Еще местами отступы поехали. Можно выделить все файлы проекта и сделать reformat code

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +    fun providePresenter() = AboutPresenter()
Не нужен provide

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        ib_telegram?.setOnClickListener {
и без "?" студия не будет ругаться. Убрать бы тут и везде ниже. И можно в одну строчку писать фигурные скобки и лямбду, также красивей)

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        Snackbar.make(my_linear, message, Snackbar.LENGTH_LONG).show()
`my_linear`  - для некоторых ресурсов нет такого айди

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +            aboutPresenter.openLink(getString(R.string.telegram))
Я тебе уже рассказал как правильно писать названия public методы презентера: это должны быть события, например, `onTelegramButtonClicked()`

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutPresenter.kt
> +            val intent = Intent(Intent.ACTION_SENDTO)
 андроид классов не должно быть в перезентере. Можешь посмотреть в импортах какие android зависимости

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutView.kt
> +    fun showMessage(message:String)
Обычно я указываю стратегии даже если она дефолтная. Например можно забыть указать стратегию, а потом думать что тут все ок. А если указывать стратегии всегда, то будет 100% понятно что ты ее выбрал осознано

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +    fun provideDetailPresenter() = NewsDetailPresenter()
провайдер не нужен

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +            aboutPresenter.openLink(getString(R.string.telegram))
И так во всех презентерах

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
>      fun newInstance(id: Int): Fragment {
У тебя этот метод должен лежать в companion object, чтобы он был статичным

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsEditor/EditorActivity.kt
> +    fun providePresenter() = NewsPresenter()
не нужен метод

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsEditor/EditorActivity.kt
> +        newsPresenter.compositeDisposable.clear()
чистить compositeDisposable надо в презентере

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        my_linear?.addView(tv)
без "?"
my_linear - не очень понятный нейминг. Можешь использовать такой нейминг для айди вьюшек: {имя разметки}_{тип элемента}_{название элемента}

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +        newsDetailPresenter.disposable.clear()
чистить надо в презентере (у moxy перезентера тоже есть методы жизненного цикла, которые можно override)
А то выходит экран повернул и запрос в сет умер. И зачем нам тогда мокси?)

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +    override fun popUp() {
непонятно название, мне кажется лучше `closeFragment()`

2019-04-14 17:59 UTC, georgyR commented on app/build.gradle
> +    kapt 'com.jakewharton:butterknife-compiler:9.0.0'
ты же переехал на kotlin полностью? Можно удалить эту зависимость

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsList/NewsListView.kt
> +interface NewsListView: MvpView {
проставь стратегии у всех методов

2019-04-14 17:59 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailView.kt
> +interface NewsDetailView:MvpView {
проставь стратегии у всех методов в интерфейсе

2019-04-15 13:29 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +    fun providePresenter() = AboutPresenter()
Убрал провайды, сделал BasePresenter.

2019-04-15 13:30 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        ib_telegram?.setOnClickListener {
Уже было исправлено. Забыл просто пушнуть
 ib_telegram?.setOnClickListener {
            aboutPresenter.openLink(getString(R.string.telegram))
        }
        ib_vk?.setOnClickListener {
            aboutPresenter.openLink(getString(R.string.vk))
        }
        ib_github?.setOnClickListener {
            aboutPresenter.openLink(getString(R.string.github))
        }
        btn_send_comment?.setOnClickListener {
            if (et_message.toString().isNotEmpty())aboutPresenter.sendMessage(et_message.toString(),this)
        }

2019-04-15 13:32 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        Snackbar.make(my_linear, message, Snackbar.LENGTH_LONG).show()
Странно, проверил по всем разметкам есть везде
android:id="@+id/my_linear"

2019-04-15 13:37 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +            aboutPresenter.openLink(getString(R.string.telegram))
Вроде переделал

2019-04-15 13:39 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutPresenter.kt
> +            val intent = Intent(Intent.ACTION_SENDTO)
Ну тут по идее Интент это намерение, т.е. это не должно быть во View, а по другому не сделаешь.

2019-04-15 13:40 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +    fun provideDetailPresenter() = NewsDetailPresenter()
Убрал уже

2019-04-15 14:52 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsEditor/EditorActivity.kt
> +    fun providePresenter() = NewsPresenter()
Убрал уже везде ProvidePresenter

2019-04-15 14:52 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsEditor/EditorActivity.kt
> +        newsPresenter.compositeDisposable.clear()
Переделал.

2019-04-15 14:55 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        my_linear?.addView(tv)
Исправил на android:id="@+id/linear_layout"

2019-04-15 14:56 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +        newsDetailPresenter.disposable.clear()
Исправил. на disposeAll

2019-04-15 14:57 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
> +    override fun popUp() {
Исправил

2019-04-15 14:59 UTC, jonart commented on app/build.gradle
> +    kapt 'com.jakewharton:butterknife-compiler:9.0.0'
Да убрал зависимость.

2019-04-15 15:02 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsList/NewsListView.kt
> +interface NewsListView: MvpView {
Проставил

2019-04-15 15:02 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailView.kt
> +interface NewsDetailView:MvpView {
Проставил

2019-04-15 15:03 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutView.kt
> +    fun showMessage(message:String)
Указал все стратегии

2019-04-19 09:42 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailFragment.kt
>      fun newInstance(id: Int): Fragment {
newInstance не ложится в companion object

2019-04-19 09:48 UTC, jonart commented
> Охренеть названия!

Не понятно на

2019-04-21 18:15 UTC, georgyR requested changes

2019-04-21 18:15 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        ib_telegram?.setOnClickListener {
Вот прям сейчас в гите вижу что у тебя все через `.?`, а надо без него

2019-04-21 18:15 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutPresenter.kt
> +            val intent = Intent(Intent.ACTION_SENDTO)
тогда activity - это действие. Зачем во вью он нужен? Немного странные аргументы не правда ли? 
Меня учили, что android классов не должно быть в презентере

2019-04-21 18:15 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/BasePresenter.kt
> +}
```
abstract class BasePresenter<View : MvpView> : MvpPresenter<View>() {
    
    private val disposable = CompositeDisposable()

    override fun onDestroy() {
        super.onDestroy()
        disposable.clear()
    }
}
```

И все, можно забыть про вызов `clear()`

2019-05-03 09:40 UTC, georgyR commented on app/src/main/java/ru/evgeniy/nytimes/fragments/newsDetailFragment/NewsDetailView.kt
> +interface NewsDetailView:MvpView {
не проставил

2019-05-03 17:58 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/activity/AboutActivity.kt
> +        ib_telegram?.setOnClickListener {
Убрал.

2019-05-03 18:01 UTC, jonart commented on app/src/main/java/ru/evgeniy/nytimes/fragments/BasePresenter.kt
> +}
переделал, private нельзя, потому что как я буду засовывать то?
Остальное переделал.

2019-05-03 20:29 UTC, georgyR approved these changes

2019-05-03 20:29 UTC, merged